// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/invitation-system/Invitations.tsx": () => import("../components/mockups/invitation-system/Invitations.tsx"),
  "./components/mockups/workflow-simple/Workflow.tsx": () => import("../components/mockups/workflow-simple/Workflow.tsx")
};
